name: Sphinx Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      # Check out the main branch
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Do not persist the token during execution of this job.
          path: main
          ref: main

      # TODO Actually Run Sphinx
      - name: Run Sphinx
        run: echo "TODO" > docs/index.html

      - name: Check for Documentation Changes
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain docs/)" ]; then echo "true"; else echo "false"; fi)

      # Check out the main branch
      - name: Checkout GitHub Pages Branch
        if: steps.git-check.outputs.modified == 'true'
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Do not persist the token during execution of this job.
          path: gh-pages
          ref: gh-pages

      # Commit changes in docs to the pages branch
      - name: "Commit changes"
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git add -A docs/
          git commit -m "From $GITHUB_REF $(echo ${GITHUB_SHA} | cut -c 1-8)"
          git push
