name: Sphinx Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Main Branch"
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Do not persist the token during execution of this job.
          path: main
          ref: main

      - name: "Checkout GitHub Pages Branch"
        if: steps.git-check.outputs.modified == 'true'
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Do not persist the token during execution of this job.
          path: gh-pages
          ref: gh-pages

      - name: "Setup Python & Install Spinx"
        uses: actions/setup-python@v3

      - name: "Install Sphinx & Theme"
        run: pip install sphinx-rtd-theme==1.0.0

      - name: "Run Sphinx"
        run: |
          sphinx-build -b html main/docs gh-pages/docs -E -d $GITHUB_WORKSPACE/.doctree

      - name: "Check for changes"
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(cd gh-pages && git status --porcelain docs/)" ]; then echo "true"; else echo "false"; fi)

      # - name: "Sync changed documentation"
      #   if: steps.git-check.outputs.modified == 'true'
      #   run: rsync -av main/docs/ gh-pages/docs

      - name: "Commit changes"
        if: steps.git-check.outputs.modified == 'true'
        run: |
          cd gh-pages
          git add -A docs/
          git config --global user.email "$(git show --format=%ae -s)"
          git config --global user.name "$(git show --format=%an -s)"
          git commit -m "From $GITHUB_REF $(echo ${GITHUB_SHA} | cut -c 1-8)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
